## 67. create ymy own Promise

### Problem

https://bigfrontend.dev/problem/create-ymy-own-Promise

### Problem Description

[Promise](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise) is widely used nowadays, hard to think how I handled [Callback Hell](http://callbackhell.com/) in the old times.

Can you implement a `MyPromise` Class by ymyself?

At least it should match following requirements

1. new promise: `new MyPromise((resolve, reject) => {})`
2. chaining : `MyPromise.prototype.then()` _[then handlers](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/then) should be called asynchronously_
3. rejection handler: `MyPromise.prototype.catch()`
4. static methods: `MyPromise.resolve()`, `MyPromise.reject()`.

This is a challenging problem. Recommend you read about Promise thoroughly first.

### Understanding the problem

Build my own `Promise` class that fulfills the following requirements:

1. the `new Promise` constructor accepts a callback function as an argument. The callback function receives two arguments: `resolve` and `reject`.
2. `MyPromise.prototype.then()` can be chained. `MyPromise.prototype.then()` takes in two callback functions, which should be executed asynchronously.
3. it should has a method `MyPromise.prototype.catch()` to handle rejection.
4. it should has two static methods: `MyPromise.resolve()`, `MyPromise.reject()`, so I can write e.g.`MyPromise.resolve('foo').then(() => {})`.

### Approach

#### The Constructor of `MyPromise`

The `promise` object created by the class `Promise` has a `state` property. The `state` is initially `pending`. So in the constructor of the `MyPromise` class, I need to define a property `state` and set it to `pending`.

#### Handle the function that is passed to `new Promise`

The function is called the **executor**. It is executed immediately and automatically by `new Promise` and is able to `resolve` or `reject` the promise. So I should call it in the `constructor` of the `MyPromise` class with the arguments `resolve` and `reject`.

🙋‍♀️🙋‍♂️ Error thrown by the executor function should be handled. If there is an error, the promise should be rejected.

#### Define `resolve` and `reject` that is passed to the executor function

A executor function that resolves the promise looks like this:

```js
function(resolve, reject) {
  setTimeout(() => {
    resolve('Done!');
  }, 1000);
}
```

A executor function that rejects the promise looks like this:

```js
 function(resolve, reject) {
  setTimeout(() => {
    reject(new Error('Something went wrong!'));
  }, 1000);
}
```

`resolve` and `reject` are both functions which receive one argument. So I should define the two methods in the class `MyPromise`.

When `resolve` is called, the `state` of the `promise` is changed to `fulfilled`, and when `reject` is called, the `state` is changed to `rejected`.

Besides the `state` property, the `promise` object should also have a `result` property to store the promise result. Initially, it is set to `undefined`. Its value changes either to the resolved value if `resolve(value)` is called, or to the rejected value if `reject(error)` is called. A `Promise` can only be resolved or rejected once.

Thus, I can define my `resolve` and `reject` like the following:

```js
_resolve(value) {
  // Ensure Promise is only resolved or rejected once.
  if (this.state !== 'pending') return;

  this.state = 'fulfilled';
  this.result = value;
}

_reject(error) {
  // Ensure Promise is only resolved or rejected once.
  if (this.state !== 'pending') return;

  this.state = 'rejected';
  this.result = error;
}
```

Since `MyPromise` will also have two static methods `resolve` and `reject`, use underscores to differentiate them.

Because class methods are not bound by default and `_resolve` or `_reject` will be called in the executor function with a plain, undecorated function reference, `this` inside both methods will be lost. Therefore I need to `bind` both methods in the `constructor` or use the experimental fat arrow class methods.

#### Define `then` method

`Promise.prototype.then()` takes up to two arguments:

1.  The first argument is a function that is invoked when the promise is resolved, and receives the result. If it is not a function, it is replaced with a function that simply returns the received result.
2.  The second argument is a function that runs when the promise is rejected, and receives the error. If it is not a function, it is replaced with a "Thrower" function.

The syntax is:

```js
promise.then(
  (result) => {
    // handle a successful result
  },
  (error) => {
    // handle an error
  }
);
```

Both arguments are optional.

The `Promise.prototype.then()` returns a `Promise`:

```js
const promise = Promise.resolve('from promise');
const thenPromise = promise.then((result) => {});

console.log(promise);
// Promise {
//   [[PromiseState]]: 'fulfilled',
//   [[PromiseResult]]: 'from promise',
// }
console.log(thenPromise);
// Promise {
//   [[PromiseState]]: 'pending',
//   [[PromiseResult]]: undefined,
// }

setTimeout(() => {
  console.log(thenPromise);
});
// Promise {
//   [[PromiseState]]: 'fulfilled',
//   [[PromiseResult]]: undefined,
// }
```

So the `then` method of the class `MyPromise` should be look like this:

```js
then(onFulfilled, onRejected) {
  return new MyPromise((resolve, reject) => {});
}
```

##### Handle the first argument in my `then` method

Since the callback function runs when the promise is resolved, it cannot be executed within the `then`.
For example:

```js
class MyPromise {
  constructor(executor) {
    this.status = 'pending';
    try {
      executor(this._resolve.bind(this), this._reject.bind(this));
    } catch (error) {
      this._reject(error);
    }
  }

  _resolve(result) {
    this.state = 'fulfilled';
    this.result = result;
  }

  then(onFulfilled) {
    onFulfilled(this.result);
    // Call onFulfilled asynchronously.
    // queueMicrotask(() => {
    //   onFulfilled(this.result);
    // });
  }
}

const p = new MyPromise((resolve) => {
  resolve(10);
}).then((result) => {
  console.log(result); // 10
});
```

Although the code above seems to work, it doesn't work as intended when the promise is resolved asynchronously, even if the `onFulfilled` is called asynchronously:

```js
const p = new MyPromise((resolve) => {
  setTimeout(() => {
    resolve(10);
  }, 0);
}).then((result) => {
  console.log(result); // undefined
});
```

Therefore, the `onFulfilled` function should be called inside the `_resolve` method. The `then` method just registers the `onFulfilled` function, so that `_resolve` knows which function to call. The `onFulfilled` function is like a subscriber, subscribing to the promised result, and the `then` method is kind of like the function `subscribe` in the Publisher/Subscriber Pattern, which receives subscriber callbacks and stores/registers them in certain data structures.

```js
class MyPromise {
  constructor(executor) {
    // ...
  }

  _resolve(value) {
    //...
    this.onFulfilled(this.result);
  }

  then(onFulfilled) {
    // If onFulfilled is not a function, replace it with a function
    // that simply returns the received result.
    this.onFulfilled =
      typeof onFulfilled === 'function' ? onFulfilled : (value) => value;
    return new Promise((resolve, reject) => {});
  }
}
```

Since the `then` method will be triggered instantly, but the callback functions (handlers) are invoked asynchronously, We can use the [queueMicrotask()](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/queueMicrotask) method to implement this.

```js
_resolve(value) {
  //...
  queueMicroTask(() => {
    this.onFulfilled(this.result);
  });
}
```

Next, I need to handle the return value returned by the `onFulfilled` function.
In the `Promise`, if the `onFulfilled` function:

- returns a value, the promise returned by `then` gets resolved with the returned value as its value.

```js
const promise = Promise.resolve('from promise');

const thenPromise = promise.then((result) => {
  return 'from then handler';
});

setTimeout(() => {
  console.log(thenPromise);
});
// Promise {
//   [[PromiseState]]: 'fulfilled',
//   [[PromiseResult]]: 'from then handler',
// }
```

- doesn't return anything, the promise returned by `then` gets resolved with an `undefined` value.

```js
const promise = Promise.resolve('from promise');

const thenPromise = promise.then((result) => {
  console.log(result); // 'from promise'
});

setTimeout(() => {
  console.log(thenPromise);
});
// Promise {
//   [[PromiseState]]: 'fulfilled',
//   [[PromiseResult]]: undefined,
// }
```

- throws an error, the promise returned by `then` gets rejected with the error as its value.

```js
const promise = Promise.resolve('from promise');

const thenPromise = promise.then((result) => {
  throw new Error('error from then handler');
});

setTimeout(() => {
  console.log(thenPromise);
});
// Promise {
//   [[PromiseState]]: 'rejected',
//   [[PromiseResult]]: Error: error from then handler.
// }
```

- returns an already fulfilled promise, the promise returned by `then` gets resolved with that promise's value as its value.

```js
const promise = Promise.resolve('from promise');

const thenPromise = promise.then((result) => {
  return Promise.resolve('resolved promise returned by then handler');
});

setTimeout(() => {
  console.log(thenPromise);
});
// Promise {
//   [[PromiseState]]: 'fulfilled',
//   [[PromiseResult]]: 'resolved promise returned by then handler',
// }
```

- returns an already rejected promise, the promise returned by `then` gets rejected with that promise's value as its value.

```js
const promise = Promise.resolve('promise');

const thenPromise = promise.then((result) => {
  return Promise.reject('rejected promise returned by then handler');
});

setTimeout(() => {
  console.log(thenPromise);
});
// Promise {
//   [[PromiseState]]: 'rejected',
//   [[PromiseResult]]: 'rejected promise returned by then handler',
// }
```

- returns a **pending** promise, the promise returned by `then` gets resolved or rejected after the the promise returned by the handler gets resolved or rejected. The resolved value of the promise returned by `then` will be the same as the resolved value of the promise returned by the handler.

```js
const promise = Promise.resolve('promise');

const thenPromise = promise.then((result) => {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      resolve('resolved promise returned by then handler');
    }, 3000);
  });
});

setTimeout(() => {
  console.log(thenPromise); // Promise {<pending>}
});

setTimeout(() => {
  console.log(thenPromise);
  // Promise {<fulfilled>: "resolved promise returned by then handler"}
}, 4000);
```

Therefore, I need to make the `resolve` and `reject` of the promise returned by `then` available in `_resolve` method, so that they can be invoked after the `onFulfilled` function is completed and receive the value returned by the `onFulfilled` function. We can create two properties in current promise object to store both functions:

```js
then(onFulfilled) {
  // ...
  return new Promise((resolve, reject) => {
    this.onFulfilledResolve = resolve;
    this.onFulfilledReject = reject;
  });
}
```

In `_resolve` I can use `try...catch` to catch the error thrown by the `onFulfilled` method. In the `catch` block, call `this.onFulfilledReject()` with the error as argument to reject the promise returned by `then`. In the `try` block, store the value returned by the `onFulfilled` method. If the returned value is a promise, the promise returned by `then` will only get fulfilled or rejected once that promise gets resolved or rejected. To accomplish this, I can call the `then` method of the returned value and pass `this.onFulfilledResolve()` and `this.onFulfilledReject()` as the `then` handlers. If the return value is not a promise, call `this.onFulfilledResolve()` with the return value as argument to resolve the promise returned by `then`.

```js
_resolve(value) {
  // ...
  queueMicroTask(() => {
    try {
      const returnValue = this.onFulfilled(this.result);
      const isReturnValueInstanceOfMyPromise = returnValue instanceof MyPromise;

      if (!isReturnValueInstanceOfMyPromise) {
        this.onFulfilledResolve(returnValue);
      } else {
        returnValue.then(
          this.onFulfilledResolve,
          this.onFulfilledReject,
        );
      }
    } catch (error) {
      this.onFulfilledReject(error);
    }
  });
}
```

In addition, before I call `this.onFulfilled`, I also need to ensure it exists, since `.then()` might not be called:

```js
const promise = Promise.resolve('foo');

promise.then((result) => {
  return 'bar';
});
// The promise returned by `then` is resolved, but there
// is no further action with the promise. Therefore, when
// the method `_resolve` of the returned promise runs,
// `this.onFulfilled` is undefined.
```

##### Handle the second argument in my `then` method

The second callback function runs when the promise is rejected. Like the first argument, `then` should register the second callback function, so that `_reject` can execute it asynchronously whenever the promise is rejected.

```js
then(onFulfilled, onRejected) {
  // ...
  this.onRejected = onRejected;
  // ...
}
```

```js
_reject(error) {
  // ...
  queueMicrotask(() => {
    try {
      this.onRejected(error);
    } catch (error) {

    }
  })
}
```

Now I need to handle the consequences of calling `onRejected`.
In the `Promise`, if the `onRejected` :

- is not a function, the `onRejected` is replaced with a function that throws the received argument, and the promise returned by `then` gets rejected with that promise's value as its value.

```js
const promise = Promise.reject('error from promise');

const thenPromise = promise.then((result) => {});

setTimeout(() => {
  console.log(thenPromise);
});
// Uncaught (in promise) error from promise
// Promise {
//   [[PromiseState]]: 'rejected',
//   [[PromiseResult]]: 'error from promise',
// }
```

- throws an error, the promise returned by `then` gets rejected with the thrown error as its value.

```js
const promise = Promise.reject('error from promise');

const thenPromise = promise.then(null, (reason) => {
  throw new Error('Error from onRejected');
});

setTimeout(() => {
  console.log(thenPromise);
});
// Promise {
//   [[PromiseState]]: 'rejected',
//   [[PromiseResult]]: Error: Error from onRejected
// }
```

- doesn't return anything, the promise returned by `then` gets resolved with an `undefined` value.

```js
const promise = Promise.reject('error from promise');

const thenPromise = promise.then(null, (reason) => {
  console.log(reason);
});

setTimeout(() => {
  console.log(thenPromise);
});
// Promise {
//   [[PromiseState]]: 'fulfilled',
//   [[PromiseResult]]: undefined
// }
```

- returns a value, the promise returned by `then` gets resolved with the returned value as its value.

```js
const promise = Promise.reject('error from promise');

const thenPromise = promise.then(null, (reason) => {
  return 'value returned by onRejected handler';
});

setTimeout(() => {
  console.log(thenPromise);
});
// Promise {
//   [[PromiseState]]: 'fulfilled',
//   [[PromiseResult]]: 'value returned by onRejected handler'
// }
```

- returns an already fulfilled promise, the promise returned by `then` gets resolved with that promise's value as its value.

```js
const promise = Promise.reject('error from promise');

const thenPromise = promise.then(null, (reason) => {
  return Promise.resolve('resolved promise returned by onRejected handler');
});

setTimeout(() => {
  console.log(thenPromise);
});
// Promise {
//   [[PromiseState]]: 'fulfilled',
//   [[PromiseResult]]: 'resolved promise returned by onRejected handler'
// }
```

- returns an already rejected promise, the promise returned by `then` gets rejected with that promise's value as its value.

```js
const promise = Promise.reject('error from promise');

const thenPromise = promise.then(null, (reason) => {
  return Promise.reject('rejected promise returned by onRejected handler');
});

setTimeout(() => {
  console.log(thenPromise);
});
// Promise {
//   [[PromiseState]]: 'rejected',
//   [[PromiseResult]]: 'rejected promise returned by onRejected handler'
// }
```

- returns a **pending** promise, the promise returned by `then` gets resolved or rejected after the promise returned by the handler gets resolved or rejected.

```js
const promise = Promise.reject('error from promise');

const thenPromise = promise.then(null, (reason) => {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      resolve('resolved promise returned by onRejected handler');
    }, 3000);
  });
});

setTimeout(() => {
  console.log(thenPromise); // Promise {<pending>}
});

setTimeout(() => {
  console.log(thenPromise);
  // Promise {<fulfilled>: "resolved promise returned by onRejected handler"}
}, 4000);
```

In my `then` method, I need to replace `onRejected` with a function that throws the 'value' it receives as argument.

```js
then(onFulfilled, onRejected) {
  // ...
  this.onRejected =
    typeof onRejected === 'function'
      ? onRejected
      : (error) => { throw error; };
  // ...
}
```

And in my `_reject` method, I first try to call `this.onRejected()` and store its return value. If the returned value is not an instance of `MyPromise`, resolve the promise returned by `then` by calling `this.onFulfilledResolve()` with the returned value as argument. Otherwise call the `then` method of the returned value with `this.onFulfilledResolve()` and `this.onFulfilledReject()` as arguments. Catch any errors thrown by `this.OnRejected()`; call `this.onFulfilledReject()` and pass the error.

```js
_reject(error) {
  // ...
  queueMicrotask(() => {
    try {
      this.onRejected(error);
    } catch (error) {

    }
  })
}
```

### Solution

```js
class MyPromise {
  constructor(executor) {
    this.status = 'pending';
    try {
      executor(this._resolve.bind(this), this._reject.bind(this));
    } catch (error) {
      this._reject(error);
    }
  }

  _resolve(value) {
    if (this.status !== 'pending') return;

    this.status = 'fulfilled';
    this.result = value;
    queueMicrotask(() => {
      if (this.onFulfilled) {
        try {
          const returnValue = this.onFulfilled(this.result);
          if (!(returnValue instanceof MyPromise)) {
            this.onFulfilledResolve(returnValue);
            return;
          }

          if (returnValue.status === 'fulfilled') {
            this.onFulfilledResolve(returnValue.result);
          } else if (returnValue.status === 'rejected') {
            this.onFulfilledReject(returnValue.error);
          }
        } catch (error) {
          this.onFulfilledReject(error);
        }
      }
    });
  }

  _reject(error) {
    if (this.status !== 'pending') return;

    this.status = 'rejected';
    this.error = error;
    queueMicrotask(() => {
      if (!this.onFulfilledReject && !this.onRejectedReject) return;
      if (this.onRejected === null) {
        this.onFulfilledReject(this.error);
        return;
      }

      try {
        const returnValue = this.onRejected(this.error);
        this.onRejectedResolve
          ? this.onRejectedResolve(returnValue)
          : this.onFulfilledResolve(returnValue);
      } catch (error) {
        this.onRejectedReject
          ? this.onRejectedReject(error)
          : this.onFulfilledReject(error);
      }
    });
  }

  then(onFulfilled, onRejected) {
    this.onFulfilled =
      typeof onFulfilled === 'function' ? onFulfilled : (value) => value;
    this.onRejected = typeof onRejected === 'function' ? onRejected : null;

    const executor = (resolve, reject) => {
      this.onFulfilledResolve = resolve;
      this.onFulfilledReject = reject;
    };
    return new MyPromise(executor);
  }

  catch(onRejected) {
    if (typeof onRejected === 'function') {
      this.onRejected = onRejected;
    }

    const executor = (resolve, reject) => {
      this.onRejectedResolve = resolve;
      this.onRejectedReject = reject;
    };
    return new MyPromise(executor);
  }

  static resolve(value) {
    return new MyPromise((resolve) => {
      resolve(value);
    });
  }

  static reject(value) {
    return new MyPromise((_, reject) => {
      reject(value);
    });
  }
}
```
